title: "🆘 Help & Support"
body:
  - type: markdown
    attributes:
      value: |
        ## 🔮 Need Help with Night God Tarot?
        
        Our community of experts is here to guide you through any challenges.

  - type: dropdown
    id: help-type
    attributes:
      label: "🎯 Type of Help Needed"
      options:
        - "🔮 Using the Tarot Reader"
        - "🤖 AI & Monica Integration Issues"  
        - "🎨 Interface & Navigation"
        - "📱 Mobile/Device Issues"
        - "🌍 Language & Translation"
        - "🔒 Account & Privacy"
        - "⚡ Performance Issues"
        - "🛠️ Technical Development"
        - "🎭 Other"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "❓ Describe the Issue"
      description: "What specific problem are you encountering?"
      placeholder: "Please describe what's happening and what you expected..."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "📋 Steps to Reproduce"
      description: "What steps led to this issue?"
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error...

  - type: textarea
    id: environment
    attributes:
      label: "💻 Environment"
      description: "What device/browser are you using?"
      placeholder: |
        - Browser: Chrome/Firefox/Safari
        - Device: Desktop/Mobile/Tablet
        - Operating System: Windows/Mac/iOS/Android

  - type: textarea
    id: additional
    attributes:
      label: "✨ Additional Information"
      description: "Anything else that might help?"
      placeholder: "Screenshots, error messages, or other relevant details..."

  - type: dropdown
    id: urgency
    attributes:
      label: "⚡ Urgency Level"
      options:
        - "🌙 Low - When convenient"
        - "⭐ Medium - This week"
        - "🔥 High - This blocks my reading"
        - "🚨 Critical - Site is broken"