title: "💡 New Feature Idea"
body:
  - type: markdown
    attributes:
      value: |
        ## 🔮 Feature Request for Night God Tarot
        
        Thank you for sharing your divine inspiration! Your ideas help shape the future of our mystical platform.

  - type: textarea
    id: feature-description
    attributes:
      label: "✨ Feature Description"
      description: "Describe your feature idea in detail"
      placeholder: "What mystical enhancement would you like to see?"
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: "🎭 Category"
      description: "Which area of the app would this enhance?"
      options:
        - "🔮 Tarot Readings & Cards"
        - "🤖 AI & Monica Integration"
        - "🎨 UI/UX Design"
        - "🌙 Spiritual Features"
        - "⚡ Performance"
        - "🔒 Security"
        - "🌍 Internationalization"
        - "📱 Mobile Experience"
        - "🎯 Other"
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: "🎯 Use Case"
      description: "How would users benefit from this feature?"
      placeholder: "Describe the spiritual journey this feature would enable..."

  - type: textarea
    id: implementation
    attributes:
      label: "🛠️ Implementation Ideas"
      description: "Any technical thoughts on how this might work?"
      placeholder: "Share your technical insights (optional)"

  - type: checkboxes
    id: expertise
    attributes:
      label: "🌟 Your Expertise"
      description: "Which areas match your professional background?"
      options:
        - label: "🎨 Web Design & UI/UX"
        - label: "🤖 AI & Machine Learning"
        - label: "⚡ Engineering & Development"
        - label: "📈 Brand & Marketing"
        - label: "🔮 Tarot & Spirituality"
        - label: "🌍 Languages & Translation"