name: 🚀 Deploy Working Site NOW
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - run: npm ci
    
    - run: npm run build
      env:
        NODE_ENV: production
        GITHUB_ACTIONS: true
        VITE_MONICA_API_KEY: ${{ secrets.VITE_MONICA_API_KEY }}
        MONICA_API_KEY: ${{ secrets.MONICA_API_KEY }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
    
    - name: Fix asset paths
      run: |
        cd dist
        sed -i 's|/night-god-tarot-unified/|./|g' index.html
        find . -name "*.js" -exec sed -i 's|/night-god-tarot-unified/|./|g' {} \;
        find . -name "*.css" -exec sed -i 's|/night-god-tarot-unified/|./|g' {} \;
    
    - uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
    
    - uses: actions/deploy-pages@v4